version: "3.9"

services:
  app:
    build:
      context: ./app
    ports:
      - "5005:5005"
      - "8501:8501"
    container_name: app
    volumes:
      - ./health_data.db:/app/health_data.db

  playwright:
    build:
      context: ./playwright
    depends_on:
      - app
    container_name: playwright
