version: "3.9"

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090" # Mapeia a porta do contêiner para a porta local
    volumes:
      - ./app:/app # Monta o código local para facilitar o desenvolvimento
    container_name: python_app_container
